include:
  - combs/compose.yaml

services:
  mariadb:
    image: mariadb:lts
    restart: always
    volumes:
      - ./mariadb-data:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
    networks:
      - hive-network

  hive-core:
    image: ghcr.io/ssh-honeypot/hive-core:master
    restart: always
    env_file:
      - .env
    expose:
      - 3000
      - 3001
      - 3002
    networks:
      - hive-network
    depends_on:
      mariadb:
        condition: service_healthy

  hive-frontend:
    image: ghcr.io/ssh-honeypot/hive-frontend:master
    restart: always
    expose:
      - 8080
    networks:
      - hive-network

networks:
  hive-network:
    name: hive-network
