include:
  - combs/compose.yaml

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}

  mariadb:
    image: mariadb:11
    restart: always
    volumes:
      - ./mariadb-data:/var/lib/mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - hive-network

  hive-core:
    image: ghcr.io/ssh-honeypot/hive-core:master
    restart: always
    environment:
      MYSQL_HOST: mariadb
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USERNAME: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      GEOIP_FAST_LOOKUP: 18
    expose:
      - 3000
      - 3001
      - 3002
    networks:
      - hive-network
    depends_on:
      - mariadb

  hive-frontend:
    image: ghcr.io/ssh-honeypot/hive-frontend:master
    restart: always
    expose:
      - 8080
    networks:
      - hive-network

networks:
  hive-network:
    name: hive-network
