include:
  - combs/compose.yaml

services:
  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - ./mariadb-data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - hive-network

  hive-core:
    image: ghcr.io/ssh-honeypot/hive-core:master
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    expose:
      - 3000
      - 3001
      - 3002
    networks:
      - hive-network

  hive-frontend:
    image: ghcr.io/ssh-honeypot/hive-frontend:master
    restart: always
    expose:
      - 8080
    networks:
      - hive-network

networks:
  hive-network:
    name: hive-network
