services:
  comb01:
    image: ghcr.io/ssh-honeypot/cowrie:main
    restart: always
    volumes:
      - ./comb01/etc:/cowrie/cowrie-git/etc
      - ./comb01/var:/cowrie/cowrie-git/var
    networks:
      - hive-network
    ports:
      - "2201:2222"

networks:
  hive-network:
    name: hive-network
